spring:
  application:
    name: moghilan-cloud-ribbon-client-load-balancer
server:
  port: 8882
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true