spring:
  application:
    name: ribbon-load-balancer
server:
  port: 8882
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/_discovery_server}
  instance:
    prefer-ip-address: true