
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/_discovery_server/
  server:
    enable-self-preservation: false
    evication-interval-timer-in-ms: 100000